// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: container_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_CONTAINER_LIST    DataType = 0
	DataType_CONTAINER_INSPECT DataType = 1
	DataType_CONTAINER_STATS   DataType = 2
	DataType_CONTAINER_EVENT   DataType = 3
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "CONTAINER_LIST",
		1: "CONTAINER_INSPECT",
		2: "CONTAINER_STATS",
		3: "CONTAINER_EVENT",
	}
	DataType_value = map[string]int32{
		"CONTAINER_LIST":    0,
		"CONTAINER_INSPECT": 1,
		"CONTAINER_STATS":   2,
		"CONTAINER_EVENT":   3,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_container_message_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_container_message_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_container_message_proto_rawDescGZIP(), []int{0}
}

type ContainerListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerInfo       `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerListData) Reset() {
	*x = ContainerListData{}
	mi := &file_container_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerListData) ProtoMessage() {}

func (x *ContainerListData) ProtoReflect() protoreflect.Message {
	mi := &file_container_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerListData.ProtoReflect.Descriptor instead.
func (*ContainerListData) Descriptor() ([]byte, []int) {
	return file_container_message_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerListData) GetContainers() []*ContainerInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ContainerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	mi := &file_container_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_container_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfo.ProtoReflect.Descriptor instead.
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return file_container_message_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ContainerStatsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*ContainerStats      `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStatsData) Reset() {
	*x = ContainerStatsData{}
	mi := &file_container_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatsData) ProtoMessage() {}

func (x *ContainerStatsData) ProtoReflect() protoreflect.Message {
	mi := &file_container_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatsData.ProtoReflect.Descriptor instead.
func (*ContainerStatsData) Descriptor() ([]byte, []int) {
	return file_container_message_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerStatsData) GetStats() []*ContainerStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ContainerStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsage   uint64                 `protobuf:"varint,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	MemoryLimit   uint64                 `protobuf:"varint,5,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,6,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	NetworkRx     uint64                 `protobuf:"varint,7,opt,name=network_rx,json=networkRx,proto3" json:"network_rx,omitempty"`
	NetworkTx     uint64                 `protobuf:"varint,8,opt,name=network_tx,json=networkTx,proto3" json:"network_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStats) Reset() {
	*x = ContainerStats{}
	mi := &file_container_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStats) ProtoMessage() {}

func (x *ContainerStats) ProtoReflect() protoreflect.Message {
	mi := &file_container_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStats.ProtoReflect.Descriptor instead.
func (*ContainerStats) Descriptor() ([]byte, []int) {
	return file_container_message_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerStats) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerStats) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ContainerStats) GetMemoryUsage() uint64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ContainerStats) GetMemoryLimit() uint64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *ContainerStats) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *ContainerStats) GetNetworkRx() uint64 {
	if x != nil {
		return x.NetworkRx
	}
	return 0
}

func (x *ContainerStats) GetNetworkTx() uint64 {
	if x != nil {
		return x.NetworkTx
	}
	return 0
}

type ContainerInspectData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inspects      []*ContainerInspect    `protobuf:"bytes,1,rep,name=inspects,proto3" json:"inspects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInspectData) Reset() {
	*x = ContainerInspectData{}
	mi := &file_container_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInspectData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInspectData) ProtoMessage() {}

func (x *ContainerInspectData) ProtoReflect() protoreflect.Message {
	mi := &file_container_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInspectData.ProtoReflect.Descriptor instead.
func (*ContainerInspectData) Descriptor() ([]byte, []int) {
	return file_container_message_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerInspectData) GetInspects() []*ContainerInspect {
	if x != nil {
		return x.Inspects
	}
	return nil
}

type ContainerInspect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Created       string                 `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Platform      string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	State         *ContainerState        `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	Config        *ContainerConfig       `protobuf:"bytes,11,opt,name=config,proto3" json:"config,omitempty"`
	Network       *ContainerNetwork      `protobuf:"bytes,12,opt,name=network,proto3" json:"network,omitempty"`
	Mounts        []*MountPoint          `protobuf:"bytes,13,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInspect) Reset() {
	*x = ContainerInspect{}
	mi := &file_container_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInspect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInspect) ProtoMessage() {}

func (x *ContainerInspect) ProtoReflect() protoreflect.Message {
	mi := &file_container_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInspect.ProtoReflect.Descriptor instead.
func (*ContainerInspect) Descriptor() ([]byte, []int) {
	return file_container_message_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerInspect) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerInspect) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerInspect) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerInspect) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *ContainerInspect) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ContainerInspect) GetState() *ContainerState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ContainerInspect) GetConfig() *ContainerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ContainerInspect) GetNetwork() *ContainerNetwork {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *ContainerInspect) GetMounts() []*MountPoint {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type ContainerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Running       bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Paused        bool                   `protobuf:"varint,3,opt,name=paused,proto3" json:"paused,omitempty"`
	Restarting    bool                   `protobuf:"varint,4,opt,name=restarting,proto3" json:"restarting,omitempty"`
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	StartedAt     string                 `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    string                 `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerState) Reset() {
	*x = ContainerState{}
	mi := &file_container_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerState) ProtoMessage() {}

func (x *ContainerState) ProtoReflect() protoreflect.Message {
	mi := &file_container_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerState.ProtoReflect.Descriptor instead.
func (*ContainerState) Descriptor() ([]byte, []int) {
	return file_container_message_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerState) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ContainerState) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *ContainerState) GetRestarting() bool {
	if x != nil {
		return x.Restarting
	}
	return false
}

func (x *ContainerState) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContainerState) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ContainerState) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

type ContainerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Env           []string               `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	Cmd           []string               `protobuf:"bytes,4,rep,name=cmd,proto3" json:"cmd,omitempty"`
	Entrypoint    []string               `protobuf:"bytes,5,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,6,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerConfig) Reset() {
	*x = ContainerConfig{}
	mi := &file_container_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerConfig) ProtoMessage() {}

func (x *ContainerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_container_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerConfig.ProtoReflect.Descriptor instead.
func (*ContainerConfig) Descriptor() ([]byte, []int) {
	return file_container_message_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerConfig) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ContainerConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ContainerConfig) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContainerConfig) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *ContainerConfig) GetEntrypoint() []string {
	if x != nil {
		return x.Entrypoint
	}
	return nil
}

func (x *ContainerConfig) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ContainerConfig) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ContainerNetwork struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	IpAddress     string                      `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Gateway       string                      `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	MacAddress    string                      `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Ports         map[string]*PortBindings    `protobuf:"bytes,4,rep,name=ports,proto3" json:"ports,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Networks      map[string]*NetworkEndpoint `protobuf:"bytes,5,rep,name=networks,proto3" json:"networks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerNetwork) Reset() {
	*x = ContainerNetwork{}
	mi := &file_container_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerNetwork) ProtoMessage() {}

func (x *ContainerNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_container_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerNetwork.ProtoReflect.Descriptor instead.
func (*ContainerNetwork) Descriptor() ([]byte, []int) {
	return file_container_message_proto_rawDescGZIP(), []int{8}
}

func (x *ContainerNetwork) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ContainerNetwork) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *ContainerNetwork) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *ContainerNetwork) GetPorts() map[string]*PortBindings {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerNetwork) GetNetworks() map[string]*NetworkEndpoint {
	if x != nil {
		return x.Networks
	}
	return nil
}

type PortBindings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bindings      []*PortBinding         `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortBindings) Reset() {
	*x = PortBindings{}
	mi := &file_container_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortBindings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortBindings) ProtoMessage() {}

func (x *PortBindings) ProtoReflect() protoreflect.Message {
	mi := &file_container_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortBindings.ProtoReflect.Descriptor instead.
func (*PortBindings) Descriptor() ([]byte, []int) {
	return file_container_message_proto_rawDescGZIP(), []int{9}
}

func (x *PortBindings) GetBindings() []*PortBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type PortBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostIp        string                 `protobuf:"bytes,1,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	HostPort      string                 `protobuf:"bytes,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortBinding) Reset() {
	*x = PortBinding{}
	mi := &file_container_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortBinding) ProtoMessage() {}

func (x *PortBinding) ProtoReflect() protoreflect.Message {
	mi := &file_container_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortBinding.ProtoReflect.Descriptor instead.
func (*PortBinding) Descriptor() ([]byte, []int) {
	return file_container_message_proto_rawDescGZIP(), []int{10}
}

func (x *PortBinding) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

func (x *PortBinding) GetHostPort() string {
	if x != nil {
		return x.HostPort
	}
	return ""
}

type NetworkEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkId     string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Gateway       string                 `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	MacAddress    string                 `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkEndpoint) Reset() {
	*x = NetworkEndpoint{}
	mi := &file_container_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEndpoint) ProtoMessage() {}

func (x *NetworkEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_container_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEndpoint.ProtoReflect.Descriptor instead.
func (*NetworkEndpoint) Descriptor() ([]byte, []int) {
	return file_container_message_proto_rawDescGZIP(), []int{11}
}

func (x *NetworkEndpoint) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *NetworkEndpoint) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *NetworkEndpoint) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *NetworkEndpoint) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

type MountPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Mode          string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	Rw            bool                   `protobuf:"varint,6,opt,name=rw,proto3" json:"rw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountPoint) Reset() {
	*x = MountPoint{}
	mi := &file_container_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountPoint) ProtoMessage() {}

func (x *MountPoint) ProtoReflect() protoreflect.Message {
	mi := &file_container_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountPoint.ProtoReflect.Descriptor instead.
func (*MountPoint) Descriptor() ([]byte, []int) {
	return file_container_message_proto_rawDescGZIP(), []int{12}
}

func (x *MountPoint) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MountPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MountPoint) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MountPoint) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *MountPoint) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *MountPoint) GetRw() bool {
	if x != nil {
		return x.Rw
	}
	return false
}

type ContainerEventData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`     // container, network, image, volume
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // start, stop, die, create, destroy
	ActorId       string                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorName     string                 `protobuf:"bytes,4,opt,name=actor_name,json=actorName,proto3" json:"actor_name,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Attrs         map[string]string      `protobuf:"bytes,6,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerEventData) Reset() {
	*x = ContainerEventData{}
	mi := &file_container_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerEventData) ProtoMessage() {}

func (x *ContainerEventData) ProtoReflect() protoreflect.Message {
	mi := &file_container_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerEventData.ProtoReflect.Descriptor instead.
func (*ContainerEventData) Descriptor() ([]byte, []int) {
	return file_container_message_proto_rawDescGZIP(), []int{13}
}

func (x *ContainerEventData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContainerEventData) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ContainerEventData) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ContainerEventData) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *ContainerEventData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ContainerEventData) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

var File_container_message_proto protoreflect.FileDescriptor

const file_container_message_proto_rawDesc = "" +
	"\n" +
	"\x17container_message.proto\x12\x02pb\"F\n" +
	"\x11ContainerListData\x121\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x11.pb.ContainerInfoR\n" +
	"containers\"w\n" +
	"\rContainerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\">\n" +
	"\x12ContainerStatsData\x12(\n" +
	"\x05stats\x18\x01 \x03(\v2\x12.pb.ContainerStatsR\x05stats\"\x80\x02\n" +
	"\x0eContainerStats\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x04R\vmemoryUsage\x12!\n" +
	"\fmemory_limit\x18\x05 \x01(\x04R\vmemoryLimit\x12%\n" +
	"\x0ememory_percent\x18\x06 \x01(\x01R\rmemoryPercent\x12\x1d\n" +
	"\n" +
	"network_rx\x18\a \x01(\x04R\tnetworkRx\x12\x1d\n" +
	"\n" +
	"network_tx\x18\b \x01(\x04R\tnetworkTx\"H\n" +
	"\x14ContainerInspectData\x120\n" +
	"\binspects\x18\x01 \x03(\v2\x14.pb.ContainerInspectR\binspects\"\xb1\x02\n" +
	"\x10ContainerInspect\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x18\n" +
	"\acreated\x18\x04 \x01(\tR\acreated\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12(\n" +
	"\x05state\x18\n" +
	" \x01(\v2\x12.pb.ContainerStateR\x05state\x12+\n" +
	"\x06config\x18\v \x01(\v2\x13.pb.ContainerConfigR\x06config\x12.\n" +
	"\anetwork\x18\f \x01(\v2\x14.pb.ContainerNetworkR\anetwork\x12&\n" +
	"\x06mounts\x18\r \x03(\v2\x0e.pb.MountPointR\x06mounts\"\xd7\x01\n" +
	"\x0eContainerState\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12\x16\n" +
	"\x06paused\x18\x03 \x01(\bR\x06paused\x12\x1e\n" +
	"\n" +
	"restarting\x18\x04 \x01(\bR\n" +
	"restarting\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\a \x01(\tR\n" +
	"finishedAt\"\x9a\x02\n" +
	"\x0fContainerConfig\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x10\n" +
	"\x03env\x18\x03 \x03(\tR\x03env\x12\x10\n" +
	"\x03cmd\x18\x04 \x03(\tR\x03cmd\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x05 \x03(\tR\n" +
	"entrypoint\x12\x1f\n" +
	"\vworking_dir\x18\x06 \x01(\tR\n" +
	"workingDir\x127\n" +
	"\x06labels\x18\a \x03(\v2\x1f.pb.ContainerConfig.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x03\n" +
	"\x10ContainerNetwork\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x18\n" +
	"\agateway\x18\x02 \x01(\tR\agateway\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\x125\n" +
	"\x05ports\x18\x04 \x03(\v2\x1f.pb.ContainerNetwork.PortsEntryR\x05ports\x12>\n" +
	"\bnetworks\x18\x05 \x03(\v2\".pb.ContainerNetwork.NetworksEntryR\bnetworks\x1aJ\n" +
	"\n" +
	"PortsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.pb.PortBindingsR\x05value:\x028\x01\x1aP\n" +
	"\rNetworksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.pb.NetworkEndpointR\x05value:\x028\x01\";\n" +
	"\fPortBindings\x12+\n" +
	"\bbindings\x18\x01 \x03(\v2\x0f.pb.PortBindingR\bbindings\"C\n" +
	"\vPortBinding\x12\x17\n" +
	"\ahost_ip\x18\x01 \x01(\tR\x06hostIp\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\tR\bhostPort\"\x8a\x01\n" +
	"\x0fNetworkEndpoint\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x18\n" +
	"\agateway\x18\x03 \x01(\tR\agateway\x12\x1f\n" +
	"\vmac_address\x18\x04 \x01(\tR\n" +
	"macAddress\"\x92\x01\n" +
	"\n" +
	"MountPoint\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\x12\x0e\n" +
	"\x02rw\x18\x06 \x01(\bR\x02rw\"\x8b\x02\n" +
	"\x12ContainerEventData\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x04 \x01(\tR\tactorName\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x127\n" +
	"\x05attrs\x18\x06 \x03(\v2!.pb.ContainerEventData.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*_\n" +
	"\bDataType\x12\x12\n" +
	"\x0eCONTAINER_LIST\x10\x00\x12\x15\n" +
	"\x11CONTAINER_INSPECT\x10\x01\x12\x13\n" +
	"\x0fCONTAINER_STATS\x10\x02\x12\x13\n" +
	"\x0fCONTAINER_EVENT\x10\x03B\x12Z\x10agent_service/pbb\x06proto3"

var (
	file_container_message_proto_rawDescOnce sync.Once
	file_container_message_proto_rawDescData []byte
)

func file_container_message_proto_rawDescGZIP() []byte {
	file_container_message_proto_rawDescOnce.Do(func() {
		file_container_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_container_message_proto_rawDesc), len(file_container_message_proto_rawDesc)))
	})
	return file_container_message_proto_rawDescData
}

var file_container_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_container_message_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_container_message_proto_goTypes = []any{
	(DataType)(0),                // 0: pb.DataType
	(*ContainerListData)(nil),    // 1: pb.ContainerListData
	(*ContainerInfo)(nil),        // 2: pb.ContainerInfo
	(*ContainerStatsData)(nil),   // 3: pb.ContainerStatsData
	(*ContainerStats)(nil),       // 4: pb.ContainerStats
	(*ContainerInspectData)(nil), // 5: pb.ContainerInspectData
	(*ContainerInspect)(nil),     // 6: pb.ContainerInspect
	(*ContainerState)(nil),       // 7: pb.ContainerState
	(*ContainerConfig)(nil),      // 8: pb.ContainerConfig
	(*ContainerNetwork)(nil),     // 9: pb.ContainerNetwork
	(*PortBindings)(nil),         // 10: pb.PortBindings
	(*PortBinding)(nil),          // 11: pb.PortBinding
	(*NetworkEndpoint)(nil),      // 12: pb.NetworkEndpoint
	(*MountPoint)(nil),           // 13: pb.MountPoint
	(*ContainerEventData)(nil),   // 14: pb.ContainerEventData
	nil,                          // 15: pb.ContainerConfig.LabelsEntry
	nil,                          // 16: pb.ContainerNetwork.PortsEntry
	nil,                          // 17: pb.ContainerNetwork.NetworksEntry
	nil,                          // 18: pb.ContainerEventData.AttrsEntry
}
var file_container_message_proto_depIdxs = []int32{
	2,  // 0: pb.ContainerListData.containers:type_name -> pb.ContainerInfo
	4,  // 1: pb.ContainerStatsData.stats:type_name -> pb.ContainerStats
	6,  // 2: pb.ContainerInspectData.inspects:type_name -> pb.ContainerInspect
	7,  // 3: pb.ContainerInspect.state:type_name -> pb.ContainerState
	8,  // 4: pb.ContainerInspect.config:type_name -> pb.ContainerConfig
	9,  // 5: pb.ContainerInspect.network:type_name -> pb.ContainerNetwork
	13, // 6: pb.ContainerInspect.mounts:type_name -> pb.MountPoint
	15, // 7: pb.ContainerConfig.labels:type_name -> pb.ContainerConfig.LabelsEntry
	16, // 8: pb.ContainerNetwork.ports:type_name -> pb.ContainerNetwork.PortsEntry
	17, // 9: pb.ContainerNetwork.networks:type_name -> pb.ContainerNetwork.NetworksEntry
	11, // 10: pb.PortBindings.bindings:type_name -> pb.PortBinding
	18, // 11: pb.ContainerEventData.attrs:type_name -> pb.ContainerEventData.AttrsEntry
	10, // 12: pb.ContainerNetwork.PortsEntry.value:type_name -> pb.PortBindings
	12, // 13: pb.ContainerNetwork.NetworksEntry.value:type_name -> pb.NetworkEndpoint
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_container_message_proto_init() }
func file_container_message_proto_init() {
	if File_container_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_container_message_proto_rawDesc), len(file_container_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_container_message_proto_goTypes,
		DependencyIndexes: file_container_message_proto_depIdxs,
		EnumInfos:         file_container_message_proto_enumTypes,
		MessageInfos:      file_container_message_proto_msgTypes,
	}.Build()
	File_container_message_proto = out.File
	file_container_message_proto_goTypes = nil
	file_container_message_proto_depIdxs = nil
}
