// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: rpc_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// message 정의
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_rpc_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AgentMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Agentid   int32                  `protobuf:"varint,1,opt,name=agentid,proto3" json:"agentid,omitempty"`
	AgentKey  string                 `protobuf:"bytes,2,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`
	Type      DataType               `protobuf:"varint,3,opt,name=type,proto3,enum=pb.DataType" json:"type,omitempty"`
	Host      string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Timestamp int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*AgentMessage_ListData
	//	*AgentMessage_InspectData
	//	*AgentMessage_StatsData
	//	*AgentMessage_EventData
	Data          isAgentMessage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_rpc_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_rpc_message_proto_rawDescGZIP(), []int{1}
}

func (x *AgentMessage) GetAgentid() int32 {
	if x != nil {
		return x.Agentid
	}
	return 0
}

func (x *AgentMessage) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *AgentMessage) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_CONTAINER_LIST
}

func (x *AgentMessage) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AgentMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentMessage) GetData() isAgentMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AgentMessage) GetListData() *ContainerListData {
	if x != nil {
		if x, ok := x.Data.(*AgentMessage_ListData); ok {
			return x.ListData
		}
	}
	return nil
}

func (x *AgentMessage) GetInspectData() *ContainerInspectData {
	if x != nil {
		if x, ok := x.Data.(*AgentMessage_InspectData); ok {
			return x.InspectData
		}
	}
	return nil
}

func (x *AgentMessage) GetStatsData() *ContainerStatsData {
	if x != nil {
		if x, ok := x.Data.(*AgentMessage_StatsData); ok {
			return x.StatsData
		}
	}
	return nil
}

func (x *AgentMessage) GetEventData() *ContainerEventData {
	if x != nil {
		if x, ok := x.Data.(*AgentMessage_EventData); ok {
			return x.EventData
		}
	}
	return nil
}

type isAgentMessage_Data interface {
	isAgentMessage_Data()
}

type AgentMessage_ListData struct {
	ListData *ContainerListData `protobuf:"bytes,11,opt,name=list_data,json=listData,proto3,oneof"`
}

type AgentMessage_InspectData struct {
	InspectData *ContainerInspectData `protobuf:"bytes,12,opt,name=inspect_data,json=inspectData,proto3,oneof"`
}

type AgentMessage_StatsData struct {
	StatsData *ContainerStatsData `protobuf:"bytes,13,opt,name=stats_data,json=statsData,proto3,oneof"`
}

type AgentMessage_EventData struct {
	EventData *ContainerEventData `protobuf:"bytes,14,opt,name=event_data,json=eventData,proto3,oneof"`
}

func (*AgentMessage_ListData) isAgentMessage_Data() {}

func (*AgentMessage_InspectData) isAgentMessage_Data() {}

func (*AgentMessage_StatsData) isAgentMessage_Data() {}

func (*AgentMessage_EventData) isAgentMessage_Data() {}

var File_rpc_message_proto protoreflect.FileDescriptor

const file_rpc_message_proto_rawDesc = "" +
	"\n" +
	"\x11rpc_message.proto\x12\x02pb\x1a\x17container_message.proto\"\x19\n" +
	"\x05Hello\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x88\x03\n" +
	"\fAgentMessage\x12\x18\n" +
	"\aagentid\x18\x01 \x01(\x05R\aagentid\x12\x1b\n" +
	"\tagent_key\x18\x02 \x01(\tR\bagentKey\x12 \n" +
	"\x04type\x18\x03 \x01(\x0e2\f.pb.DataTypeR\x04type\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x124\n" +
	"\tlist_data\x18\v \x01(\v2\x15.pb.ContainerListDataH\x00R\blistData\x12=\n" +
	"\finspect_data\x18\f \x01(\v2\x18.pb.ContainerInspectDataH\x00R\vinspectData\x127\n" +
	"\n" +
	"stats_data\x18\r \x01(\v2\x16.pb.ContainerStatsDataH\x00R\tstatsData\x127\n" +
	"\n" +
	"event_data\x18\x0e \x01(\v2\x16.pb.ContainerEventDataH\x00R\teventDataB\x06\n" +
	"\x04dataB\x12Z\x10agent_service/pbb\x06proto3"

var (
	file_rpc_message_proto_rawDescOnce sync.Once
	file_rpc_message_proto_rawDescData []byte
)

func file_rpc_message_proto_rawDescGZIP() []byte {
	file_rpc_message_proto_rawDescOnce.Do(func() {
		file_rpc_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_message_proto_rawDesc), len(file_rpc_message_proto_rawDesc)))
	})
	return file_rpc_message_proto_rawDescData
}

var file_rpc_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_message_proto_goTypes = []any{
	(*Hello)(nil),                // 0: pb.Hello
	(*AgentMessage)(nil),         // 1: pb.AgentMessage
	(DataType)(0),                // 2: pb.DataType
	(*ContainerListData)(nil),    // 3: pb.ContainerListData
	(*ContainerInspectData)(nil), // 4: pb.ContainerInspectData
	(*ContainerStatsData)(nil),   // 5: pb.ContainerStatsData
	(*ContainerEventData)(nil),   // 6: pb.ContainerEventData
}
var file_rpc_message_proto_depIdxs = []int32{
	2, // 0: pb.AgentMessage.type:type_name -> pb.DataType
	3, // 1: pb.AgentMessage.list_data:type_name -> pb.ContainerListData
	4, // 2: pb.AgentMessage.inspect_data:type_name -> pb.ContainerInspectData
	5, // 3: pb.AgentMessage.stats_data:type_name -> pb.ContainerStatsData
	6, // 4: pb.AgentMessage.event_data:type_name -> pb.ContainerEventData
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_rpc_message_proto_init() }
func file_rpc_message_proto_init() {
	if File_rpc_message_proto != nil {
		return
	}
	file_container_message_proto_init()
	file_rpc_message_proto_msgTypes[1].OneofWrappers = []any{
		(*AgentMessage_ListData)(nil),
		(*AgentMessage_InspectData)(nil),
		(*AgentMessage_StatsData)(nil),
		(*AgentMessage_EventData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_message_proto_rawDesc), len(file_rpc_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_message_proto_goTypes,
		DependencyIndexes: file_rpc_message_proto_depIdxs,
		MessageInfos:      file_rpc_message_proto_msgTypes,
	}.Build()
	File_rpc_message_proto = out.File
	file_rpc_message_proto_goTypes = nil
	file_rpc_message_proto_depIdxs = nil
}
