// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: rpc_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpc_service_proto protoreflect.FileDescriptor

const file_rpc_service_proto_rawDesc = "" +
	"\n" +
	"\x11rpc_service.proto\x12\x02pb\x1a\x11rpc_message.proto\x1a\x14server_message.proto\x1a\x12test_message.proto2\xe3\x01\n" +
	"\x10ContainerService\x12'\n" +
	"\vConnMessage\x12\t.pb.Hello\x1a\t.pb.Hello(\x010\x01\x125\n" +
	"\n" +
	"DataStream\x12\x10.pb.AgentMessage\x1a\x11.pb.ServerMessage(\x010\x01\x128\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\x125\n" +
	"\x0eContainerState\x12\x10.pb.AgentMessage\x1a\x11.pb.ServerMessageB\x12Z\x10agent_service/pbb\x06proto3"

var file_rpc_service_proto_goTypes = []any{
	(*Hello)(nil),             // 0: pb.Hello
	(*AgentMessage)(nil),      // 1: pb.AgentMessage
	(*LoginUserRequest)(nil),  // 2: pb.LoginUserRequest
	(*ServerMessage)(nil),     // 3: pb.ServerMessage
	(*LoginUserResponse)(nil), // 4: pb.LoginUserResponse
}
var file_rpc_service_proto_depIdxs = []int32{
	0, // 0: pb.ContainerService.ConnMessage:input_type -> pb.Hello
	1, // 1: pb.ContainerService.DataStream:input_type -> pb.AgentMessage
	2, // 2: pb.ContainerService.LoginUser:input_type -> pb.LoginUserRequest
	1, // 3: pb.ContainerService.ContainerState:input_type -> pb.AgentMessage
	0, // 4: pb.ContainerService.ConnMessage:output_type -> pb.Hello
	3, // 5: pb.ContainerService.DataStream:output_type -> pb.ServerMessage
	4, // 6: pb.ContainerService.LoginUser:output_type -> pb.LoginUserResponse
	3, // 7: pb.ContainerService.ContainerState:output_type -> pb.ServerMessage
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_service_proto_init() }
func file_rpc_service_proto_init() {
	if File_rpc_service_proto != nil {
		return
	}
	file_rpc_message_proto_init()
	file_server_message_proto_init()
	file_test_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_service_proto_rawDesc), len(file_rpc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_service_proto_goTypes,
		DependencyIndexes: file_rpc_service_proto_depIdxs,
	}.Build()
	File_rpc_service_proto = out.File
	file_rpc_service_proto_goTypes = nil
	file_rpc_service_proto_depIdxs = nil
}
