// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: server_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_ACK               CommandType = 0
	CommandType_START_CONTAINER   CommandType = 1
	CommandType_STOP_CONTAINER    CommandType = 2
	CommandType_RESTART_CONTAINER CommandType = 3
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "ACK",
		1: "START_CONTAINER",
		2: "STOP_CONTAINER",
		3: "RESTART_CONTAINER",
	}
	CommandType_value = map[string]int32{
		"ACK":               0,
		"START_CONTAINER":   1,
		"STOP_CONTAINER":    2,
		"RESTART_CONTAINER": 3,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_message_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_server_message_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_server_message_proto_rawDescGZIP(), []int{0}
}

type ServerMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Command         CommandType            `protobuf:"varint,1,opt,name=command,proto3,enum=pb.CommandType" json:"command,omitempty"`
	TargetContainer string                 `protobuf:"bytes,2,opt,name=target_container,json=targetContainer,proto3" json:"target_container,omitempty"`
	Host            string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_server_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_server_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_server_message_proto_rawDescGZIP(), []int{0}
}

func (x *ServerMessage) GetCommand() CommandType {
	if x != nil {
		return x.Command
	}
	return CommandType_ACK
}

func (x *ServerMessage) GetTargetContainer() string {
	if x != nil {
		return x.TargetContainer
	}
	return ""
}

func (x *ServerMessage) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

var File_server_message_proto protoreflect.FileDescriptor

const file_server_message_proto_rawDesc = "" +
	"\n" +
	"\x14server_message.proto\x12\x02pb\"y\n" +
	"\rServerMessage\x12)\n" +
	"\acommand\x18\x01 \x01(\x0e2\x0f.pb.CommandTypeR\acommand\x12)\n" +
	"\x10target_container\x18\x02 \x01(\tR\x0ftargetContainer\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host*V\n" +
	"\vCommandType\x12\a\n" +
	"\x03ACK\x10\x00\x12\x13\n" +
	"\x0fSTART_CONTAINER\x10\x01\x12\x12\n" +
	"\x0eSTOP_CONTAINER\x10\x02\x12\x15\n" +
	"\x11RESTART_CONTAINER\x10\x03B\x12Z\x10agent_service/pbb\x06proto3"

var (
	file_server_message_proto_rawDescOnce sync.Once
	file_server_message_proto_rawDescData []byte
)

func file_server_message_proto_rawDescGZIP() []byte {
	file_server_message_proto_rawDescOnce.Do(func() {
		file_server_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_message_proto_rawDesc), len(file_server_message_proto_rawDesc)))
	})
	return file_server_message_proto_rawDescData
}

var file_server_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_server_message_proto_goTypes = []any{
	(CommandType)(0),      // 0: pb.CommandType
	(*ServerMessage)(nil), // 1: pb.ServerMessage
}
var file_server_message_proto_depIdxs = []int32{
	0, // 0: pb.ServerMessage.command:type_name -> pb.CommandType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_server_message_proto_init() }
func file_server_message_proto_init() {
	if File_server_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_message_proto_rawDesc), len(file_server_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_message_proto_goTypes,
		DependencyIndexes: file_server_message_proto_depIdxs,
		EnumInfos:         file_server_message_proto_enumTypes,
		MessageInfos:      file_server_message_proto_msgTypes,
	}.Build()
	File_server_message_proto = out.File
	file_server_message_proto_goTypes = nil
	file_server_message_proto_depIdxs = nil
}
